# Generated by Django 2.2.20 on 2021-04-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacancy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='category',
            new_name='company',
        ),
    ]
